---
apiVersion: v1
kind: Secret
metadata:
  name: cp4dinstaller-sensitive-data
  namespace: ${ namespace }
type: Opaque
data:
  docker-registry-username: "${ docker_username_encoded }"
  docker-registry-password: "${ docker_registry_password_encoded }"
