---
apiVersion: batch/v1
kind: Job
metadata:
  name: cloud-installer # -$ID
  labels:
    app: cp4data-installer # -$ID
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: cp4data-installer # -$ID
      annotations:
        productName: IBM Cloud Pak for Data
        productVersion: 3.5.0
    spec:
      containers:
      - env:
        - name: NAMESPACE
          value: ${ namespace }
        - name: STORAGE_CLASS
          value: ${ storage_class_name }
        - name: DOCKER_REGISTRY
          value: ${ docker_registry }
        - name: DOCKER_USERNAME
          valueFrom:
            secretKeyRef:
              name: cp4dinstaller-sensitive-data
              key: docker-registry-username
        - name: DOCKER_REGISTRY_USER
          valueFrom:
            secretKeyRef:
              name: cp4dinstaller-sensitive-data
              key: docker-registry-username
        - name: DOCKER_REGISTRY_PASS
          valueFrom:
            secretKeyRef:
              name: cp4dinstaller-sensitive-data
              key: docker-registry-password
        - name: DEPLOY_WKC
          value: "${ install_WKC }"
        - name: DEPLOY_WSL
          value: "${ install_WSL }"
        - name: DEPLOY_WML
          value: "${ install_WML }"
        - name: DEPLOY_AIOPENSCALE
          value: "${ install_AIOPENSCALE }"
        - name: DEPLOY_DV
          value: "${ install_DV }"
        - name: DEPLOY_STREAMS
          value: "${ install_STREAMS }"
        - name: DEPLOY_CDE
          value: "${ install_CDE }"
        - name: DEPLOY_SPARK
          value: "${ install_SPARK }"
        - name: DEPLOY_DB2WH
          value: "${ install_DB2WH }"
        - name: DEPLOY_DATAGATE
          value: "${ install_DATAGATE }"
        - name: DEPLOY_RSTUDIO
          value: "${ install_RSTUDIO }"
        - name: DEPLOY_DMC
          value: "${ install_DMC }"
        name: installer
        image: ${ docker_registry }/cp4d-installer:3.5.0-amd64
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: 1
        command: [ "/bin/sh", "-c" ]
        args: [ "./deploy-cp4data.sh; sleep 300" ]
      serviceAccountName: cpdinstall
      imagePullSecrets:
      - name: icp4d-anyuid-docker-pull
      restartPolicy: Never
