---
apiVersion: batch/v1
kind: Job
metadata:
  name: cloud-installer # -$ID
  labels:
    app: cp4data-installer # -$ID
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: cp4data-installer # -$ID
      annotations:
        productName: IBM Cloud Pak for Data
        productVersion: 3.5.0
    spec:
      containers:
      - env:
        - name: NAMESPACE
          value: ${ namespace }
        - name: STORAGE_CLASS
          value: ${ storage_class_name }
        - name: DOCKER_REGISTRY
          value: ${ docker_registry }
        - name: DOCKER_USERNAME
          valueFrom:
            secretKeyRef:
              name: cp4dinstaller-sensitive-data
              key: docker-registry-username
        - name: DOCKER_REGISTRY_USER
          valueFrom:
            secretKeyRef:
              name: cp4dinstaller-sensitive-data
              key: docker-registry-username
        - name: DOCKER_REGISTRY_PASS
          valueFrom:
            secretKeyRef:
              name: cp4dinstaller-sensitive-data
              key: docker-registry-password
        - name: DEPLOY_WKC
          value: "${ install_watson_knowledge_catalog }"
        - name: DEPLOY_WSL
          value: "${ install_watson_studio }"
        - name: DEPLOY_WML
          value: "${ install_watson_machine_learning }"
        - name: DEPLOY_AIOPENSCALE
          value: "${ install_watson_open_scale }"
        - name: DEPLOY_DV
          value: "${ install_data_virtualization }"
        - name: DEPLOY_STREAMS
          value: "${ install_streams }"
        - name: DEPLOY_CDE
          value: "${ install_analytics_dashboard }"
        - name: DEPLOY_SPARK
          value: "${ install_spark }"
        - name: DEPLOY_DB2WH
          value: "${ install_db2_warehouse }"
        - name: DEPLOY_DATAGATE
          value: "${ install_db2_data_gate }"
        - name: DEPLOY_RSTUDIO
          value: "${ install_rstudio }"
        - name: DEPLOY_DMC
          value: "${ install_db2_data_management }"
        name: installer
        image: ${ docker_registry }/cp4d-installer:3.5.0-amd64
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: 1
        command: [ "/bin/sh", "-c" ]
        args: [ "./deploy-cp4data.sh; sleep 300" ]
      serviceAccountName: cpdinstall
      imagePullSecrets:
      - name: icp4d-anyuid-docker-pull
      restartPolicy: Never
